import { ArrowRight, Handshake, HeartHandshake, ShieldCheck, Sprout, Target } from "lucide-react";
import { Link } from "wouter";

const values = [[ShieldCheck, "Integrity", "Straightforward communication and dependable commitments."], [Sprout, "Quality", "A quality-first lens from origin to delivery."], [Handshake, "Reliability", "Trade support built on consistency and clear follow-through."], [HeartHandshake, "Sustainability", "Respect for growers, materials, and the future of supply." ]];

export default function About() {
  return <>
    <section className="bg-[#073c2d] py-20 text-white"><div className="section-shell grid items-end gap-10 md:grid-cols-[1fr_.7fr]"><div><p className="eyebrow text-[#f4df9d]">About DivineGrow LLP</p><h1 className="display mt-4 max-w-3xl text-5xl font-semibold leading-tight md:text-6xl">Trade trust is built one shipment at a time.</h1></div><p className="text-base leading-8 text-[#c7d7cd]">A New Delhi based spice trading company serving buyers who need consistent quality, practical support, and a partner who communicates clearly.</p></div></section>
    <section className="section-pad"><div className="section-shell grid items-center gap-12 md:grid-cols-[.9fr_1.1fr] md:gap-24"><div className="relative overflow-hidden rounded-[2rem]"><img src="/manus-storage/divinegrow-saffron_0119df15.jpg" alt="Saffron, mace, nutmeg, and cinnamon" className="h-[480px] w-full object-cover" /><div className="absolute bottom-5 left-5 right-5 rounded-2xl border border-white/30 bg-[#073c2d]/75 p-5 text-white backdrop-blur-md"><p className="eyebrow text-[#f4df9d]">Our lens</p><p className="mt-2 text-sm leading-6">Quality, origin, and consistency are the details that make a difference.</p></div></div><div><p className="eyebrow">Why we exist</p><h2 className="display mt-4 text-4xl font-semibold leading-tight text-[#073c2d] md:text-5xl">Making premium Indian spice trade easier to trust.</h2><div className="mt-6 gold-line" /><p className="mt-6 text-base leading-8 text-[#66716b]">DivineGrow LLP is focused on creating lasting business relationships through careful sourcing, transparent conversations, and service that respects the buyer's time.</p><p className="mt-5 text-base leading-8 text-[#66716b]">We bring together trusted grower and processor relationships with a market-aware approach—so you can source with more confidence and less friction.</p><Link href="/products" className="mt-7 inline-flex items-center gap-2 font-bold text-[#0b6e4f] no-underline">Explore our collection <ArrowRight size={17} /></Link></div></div></section>
    <section className="bg-[#e8f1ec] py-20"><div className="section-shell"><div className="grid gap-10 md:grid-cols-2"><div className="rounded-3xl bg-[#0b6e4f] p-8 text-white md:p-10"><Target className="text-[#f4df9d]" /><p className="eyebrow mt-8 text-[#f4df9d]">Mission</p><h2 className="display mt-3 text-3xl font-semibold">Premium quality, lasting relationships.</h2><p className="mt-5 text-sm leading-7 text-[#d6e4d9]">To provide premium quality spices while building lasting business relationships through trust and consistency.</p></div><div className="rounded-3xl bg-white p-8 shadow-sm md:p-10"><p className="eyebrow">Vision</p><h2 className="display mt-3 text-3xl font-semibold text-[#073c2d]">A preferred global supplier of premium spices.</h2><p className="mt-5 text-sm leading-7 text-[#66716b]">To become a preferred global supplier of premium spices, known for product quality, integrity, and dependable trade support.</p><div className="mt-8 grid grid-cols-2 gap-3 text-sm font-bold text-[#0b6e4f]"><span>Integrity</span><span>Quality</span><span>Reliability</span><span>Customer satisfaction</span></div></div></div></div></section>
  </>;
}
