import { Clock3, Mail, MapPin, Phone } from "lucide-react";
import EnquiryForm from "@/components/EnquiryForm";

export default function Contact() {
  return <>
    <section className="bg-[#073c2d] py-20 text-white"><div className="section-shell"><p className="eyebrow text-[#f4df9d]">Contact us</p><h1 className="display mt-4 max-w-2xl text-5xl font-semibold leading-tight md:text-6xl">Good conversations start here.</h1><p className="mt-6 max-w-xl text-base leading-8 text-[#c7d7cd]">Reach out for product information, partnership conversations, or help with your next spice requirement.</p></div></section>
    <section className="section-pad"><div className="section-shell grid gap-12 lg:grid-cols-[.75fr_1.25fr] lg:items-start"><div><p className="eyebrow">DivineGrow LLP</p><h2 className="display mt-3 text-4xl font-semibold leading-tight text-[#073c2d]">Based in New Delhi. Open to the world.</h2><div className="mt-8 space-y-5"><ContactItem Icon={MapPin} title="Office" text={<>#397, Dwarka, Sector-18<br />New Delhi - 110075, India</>} href="https://maps.google.com/?q=Dwarka+Sector+18+New+Delhi" /><ContactItem Icon={Phone} title="Phone" text="+91 9871496262" href="tel:+919871496262" /><ContactItem Icon={Mail} title="Email" text="cemde.pankaj@gmail.com" href="mailto:cemde.pankaj@gmail.com" /><ContactItem Icon={Clock3} title="Working hours" text="Monday-Saturday · 9:00 AM-6:00 PM IST" /></div><a href="https://maps.google.com/?q=Dwarka+Sector+18+New+Delhi" target="_blank" rel="noreferrer" className="mt-8 block overflow-hidden rounded-2xl border border-[#dfe8e1] bg-[#e8f1ec] p-5 no-underline"><div className="flex h-28 items-center justify-center rounded-xl bg-[radial-gradient(circle_at_center,#b7d8bf_1px,transparent_1px)] [background-size:14px_14px]"><div className="rounded-full bg-[#0b6e4f] px-4 py-2 text-xs font-bold text-white shadow-lg">Open location in Google Maps</div></div></a></div><EnquiryForm kind="contact" /></div></section>
  </>;
}

function ContactItem({ Icon, title, text, href }: { Icon: typeof MapPin; title: string; text: React.ReactNode; href?: string }) { const content = <div className="flex gap-4"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-[#e8f1ec] text-[#0b6e4f]"><Icon size={18} /></div><div><p className="text-xs font-bold uppercase tracking-widest text-[#d4a017]">{title}</p><p className="mt-1 text-sm leading-6 text-[#66716b]">{text}</p></div></div>; return href ? <a href={href} target={href.startsWith("http") ? "_blank" : undefined} rel={href.startsWith("http") ? "noreferrer" : undefined} className="block no-underline hover:opacity-80">{content}</a> : content; }
