import { ArrowRight, Check, Package, Sparkles } from "lucide-react";
import { Link } from "wouter";
import { products } from "@/lib/products";

export default function Products() {
  return <>
    <section className="bg-[#073c2d] py-20 text-white"><div className="section-shell"><p className="eyebrow text-[#f4df9d]">Our collection</p><h1 className="display mt-4 max-w-3xl text-5xl font-semibold leading-tight md:text-6xl">Spices, seeds & staples, carefully sourced.</h1><p className="mt-6 max-w-2xl text-base leading-8 text-[#c7d7cd]">From high-aroma cardamom to premium saffron, nutritious fox nuts, and everyday pantry staples, explore the products we supply to food businesses, distributors, and trade buyers.</p></div></section>
    <section className="section-pad"><div className="section-shell"><div className="grid gap-6 md:grid-cols-2">{products.map((product, index) => <article id={product.slug} key={product.slug} className="scroll-mt-28 overflow-hidden rounded-3xl border border-[#dfe8e1] bg-white shadow-sm transition hover:-translate-y-1 hover:shadow-xl hover:shadow-[#073c2d]/10"><div className="grid sm:grid-cols-2"><div className="relative h-[280px] overflow-hidden sm:h-[340px] sm:min-h-0"><img src={product.image} alt={`${product.name} whole spice`} className="absolute inset-0 h-full w-full object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-[#073c2d]/65 via-transparent to-transparent" /><span className="absolute bottom-5 left-5 rounded-full bg-white/90 px-3 py-1 text-[10px] font-bold uppercase tracking-widest text-[#073c2d]">0{index + 1} · {product.origin}</span></div><div className="p-6 sm:p-7"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-[#d4a017]">{product.scientific || "Whole spice"}</p><h2 className="display mt-2 text-3xl font-semibold text-[#073c2d]">{product.name}</h2></div><Sparkles size={18} className="mt-1 shrink-0 text-[#d4a017]" /></div><p className="mt-4 text-sm leading-7 text-[#66716b]">{product.description}</p><div className="mt-5 grid gap-4 text-xs sm:grid-cols-2"><div><p className="font-bold uppercase tracking-widest text-[#073c2d]">Best for</p><ul className="mt-2 space-y-1 text-[#66716b]">{product.uses.slice(0, 3).map((use) => <li key={use} className="flex gap-2"><Check size={13} className="mt-0.5 text-[#0b6e4f]" />{use}</li>)}</ul></div><div><p className="font-bold uppercase tracking-widest text-[#073c2d]">Pack formats</p><p className="mt-2 leading-5 text-[#66716b]">{product.packaging.join(" · ")}</p><p className="mt-2 flex items-center gap-1 text-[#0b6e4f]"><Package size={13} />Trade volumes available</p></div></div><Link href={`/request-quote?product=${product.slug}`} className="mt-6 inline-flex items-center gap-2 text-sm font-bold text-[#0b6e4f] no-underline">Ask about {product.name} <ArrowRight size={15} /></Link></div></div></article>)}</div></div></section>
    <section className="bg-[#e8f1ec] py-16"><div className="section-shell flex flex-col items-start justify-between gap-6 md:flex-row md:items-center"><div><p className="eyebrow">Need a specific grade or volume?</p><h2 className="display mt-3 text-3xl font-semibold text-[#073c2d]">Let's discuss your requirements.</h2></div><Link href="/request-quote" className="rounded-full bg-[#0b6e4f] px-6 py-3.5 text-sm font-bold text-white no-underline">Request a quote <ArrowRight className="ml-1 inline" size={16} /></Link></div></section>
  </>;
}
